# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
# - set -o pipefail && xcodebuild test -workspace Example/Flarelight.xcworkspace -scheme Flarelight-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
  - xctool -workspace Example/Flarelight.xcworkspace -scheme Flarelight-Example -destination name="iPhone 6s" -sdk iphonesimulator CODE_SIGN_ENTITLEMENTS="" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
